import re
inputfile = open("stops.txt")                    
outputfile = open("output.txt","w+") 

for line in inputfile:
	line = line.replace('Fs/Nb','NB')
	line = line.replace('Fs/ Nb','NB')
	line = line.replace('Mb/Nb','NB')
	line = line.replace('Mb Nb','NB')
	line = line.replace('Ns/Nb','NB')
	line = line.replace('NS/NB','NB')
	line = line.replace('Ns Nb','NB')
	line = line.replace('Nb Mb','NB')
	line = line.replace('NbNs','NB')
	line = line.replace('Nb Ns','NB')
	line = line.replace('F/Nb','NB')
	line = line.replace('Fs Nb','NB')
	line = line.replace('FS/NB','NB')
	line = line.replace('Nb Fs','NB')
	line = line.replace('F/Nb','NB')
	line = line.replace('Fsnb','NB')
	line = line.replace('Fs Nb','NB')
	line = line.replace('Nb Fs','NB')
	line = line.replace('FsNb','NB')
	line = line.replace('NsEb','EB')
	line = line.replace('Ns/Eb','EB')
	line = line.replace('Mb/Eb','EB')
	line = line.replace('Mbeb','EB')
	line = line.replace('Mb Eb','EB')
	line = line.replace('Eb/Fs','EB')
	line = line.replace('Eb Fs','EB')
	line = line.replace('Fs Eb','EB')
	line = line.replace('Fseb','EB')
	line = line.replace('FS EB','EB')
	line = line.replace('Fs/Eb','EB')
	line = line.replace('Ns Eb','EB')
	line = line.replace('Nseb','EB')
	line = line.replace('Fs/ Eb','EB')
	line = line.replace('FsEb','EB')
	line = line.replace('Ns Sb','SB')
	line = line.replace('NsSb','SB')
	line = line.replace('Nssb','SB')
	line = line.replace('Ns/Sb','SB')
	line = line.replace('Fssb','SB')
	line = line.replace('Fs/Sb','SB')
	line = line.replace('Fs Sb','SB')
	line = line.replace('FsSb','SB')
	line = line.replace('Sb Fs','SB')
	line = line.replace('Sb/Ns','SB')
	line = line.replace('Sb Ns','SB')
	line = line.replace('Mb/Sb','SB')
	line = line.replace('Mb Sb','SB')
	line = line.replace('Ns Wb','WB')
	line = line.replace('NsWb','WB')
	line = line.replace('Nswb','WB')
	line = line.replace('Ns/Wb','WB')
	line = line.replace('Wb/Ns','WB')
	line = line.replace('Wb/Fs','WB')
	line = line.replace('Fs Wb','WB')
	line = line.replace('FsWb','WB')
	line = line.replace('Fswb','WB')
	line = line.replace('Fs/Wb','WB')
	line = line.replace('Fs W','WB')
	line = line.replace('Mb/Wb','WB')
	line = line.replace('Mb Wb','WB')
	
	outputfile.write(line)


			


			

